### ISSUE TITLE
Events linked to BP Group on multisite

### ISSUE THREAD

**Issue by danaskallman** [christianwach/bp-event-organiser#1]
I am testing this out and when network enabled on a sub-site I see the group I am an administrator on and I can select that group however it doesn't show up in the group itself. Is this not an intended use case? Basically I am trying to figure out how group administrators can add events to their groups.

**Comment by christianwach** [comment]
@danaskallman You'd be better off trying [this fork](https://github.com/cuny-academic-commons/bp-event-organiser) which is far more advanced than this one.

**Comment by danaskallman** [comment]
Awesome, that's what I was looking for @christianwach, thanks!
