### ISSUE TITLE
Where is the event assigned to the buddypress group

### ISSUE THREAD

**Issue by wyde22** [christianwach/bp-event-organiser#2]
Hi,

I'm using your plugin and i can see in an event a metabox with all buddypress group. Then, i assign my event to a buddypress group

Now where is the event assigned ? I can't see this event in buddyspress groups home

I searched in widget menu, in the metaboxe of group buddypress ...

I can see any event in buddypress group

Thanks

**Comment by christianwach** [comment]
@wyde22 Please don't use this repo - use the one at the following link which far more developed:

https://github.com/cuny-academic-commons/bp-event-organiser

**Comment by wyde22** [comment]
hi, thanks so lot :)
